In [5]:
import numpy as np

In [6]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [7]:
# Вычисляем среднее значение по каждой строке
row_means = np.mean(matrix, axis=1, keepdims=True)

# Вычитаем среднее значение из каждой строки матрицы
result_matrix = matrix - row_means

In [8]:
print("\nРезультат после вычитания среднего значения из каждой строки:")
print(result_matrix)


Результат после вычитания среднего значения из каждой строки:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
